# This dockerfile is used to create containers that run a web
# server allowing access to the google-play-api (see
# https://github.com/facundoolano/google-play-api)

FROM ubuntu:18.04

WORKDIR /gplay_api

RUN apt-get update && apt-get install -y git

# clone google play api repo
RUN git clone https://github.com/facundoolano/google-play-api.git
WORKDIR google-play-api

# set google play api to commit that we know works. If the repo
# gets updated it may be wise to set the commit hash below to the new HEAD.
RUN git reset 6d0e649a1f50ef26721f911032292f87e4f1383c --hard

# install node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y --no-install-recommends nodejs
RUN apt-get install -y npm

# install google-play-api with npm
RUN npm install

# the server runs on port 3000
EXPOSE 3000

# the server should start when the container is started
CMD npm start
